services:
    database:
        container_name: k2h_database
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: k2hrootpw
            MYSQL_DATABASE: k2h
            MYSQL_USER: k2husr
            MYSQL_PASSWORD: k2hpw
        volumes:
            - db:/var/lib/mysql
        networks:
            - network
    saci:
        container_name: k2h_saci
        build:
            context: ./apps/saci
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - database
        networks:
            - network
    apps-frax:
        container_name: k2h_frax
        build:
            context: ./apps/frax
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    apps-cp:
        container_name: k2h_cp
        build:
            context: ./apps/cp
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    proxy:
        container_name: k2h_proxy
        build:
            context: ./proxy
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - network
    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            HIDE_PHP_VERSION: true
        depends_on:
            - database
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    db:
