services:
    ##  NGINX  ##
    nginx:
        container_name: k2h_nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        networks:
            - k2h_network
    ##  APACHE2  ##
    apache2:
        container_name: k2h_apache2
        build:
            context: ./apache2
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - k2h_network
    ##  MYSQL  ##
    mysql:
        container_name: k2h_mysql
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: johnpw
            MYSQL_DATABASE: john
            MYSQL_USER: john
            MYSQL_PASSWORD: johnpw
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - k2h_network
    ##  PHPMYADMIN  ##
    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - k2h_network
networks:
    k2h_network:
        driver: bridge
volumes:
    db:
