services:
    database:
        container_name: k2h_database
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: k2hrootpw
            MYSQL_DATABASE: k2h
            MYSQL_USER: k2husr
            MYSQL_PASSWORD: k2hpw
        volumes:
            - db:/var/lib/mysql
        networks:
            - network
    saci:
        container_name: k2h_saci
        build:
            context: ./apps/saci
            dockerfile: Dockerfile
        restart: unless-stopped
        depends_on:
            - database
        networks:
            - network
    apps-frax:
        container_name: k2h_frax
        build:
            context: ./apps/frax
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    apps-cp:
        container_name: k2h_cp
        build:
            context: ./apps/cp
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    apps-auth:
        container_name: k2h_auth
        build:
            context: ./apps/auth
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    proxy:
        container_name: k2h_proxy
        build:
            context: ./proxy
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        depends_on:
            - saci
            - apps-frax
            - apps-cp
        networks:
            - network
    mailserver:
        image: ghcr.io/docker-mailserver/docker-mailserver:latest
        container_name: k2h_mailserver
        hostname: mail.key2host.com
        env_file: mailsrv/mailserver.env
        ports:
            - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
            - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
            - "465:465"  # ESMTP (implicit TLS)
            - "587:587"  # ESMTP (explicit TLS => STARTTLS)
            - "993:993"  # IMAP4 (implicit TLS)
        volumes:
             - ./docker-data/dms/mail-data/:/var/mail/
             - ./docker-data/dms/mail-state/:/var/mail-state/
             - ./docker-data/dms/mail-logs/:/var/log/mail/
             - ./docker-data/dms/config/:/tmp/docker-mailserver/
             - /etc/localtime:/etc/localtime:ro
        restart: always
        stop_grace_period: 1m
        cap_add:
           - NET_ADMIN
        healthcheck:
            test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
            timeout: 3s
            retries: 0
        networks:
            - network
    roundcube:
        image: roundcube/roundcubemail:latest
        container_name: k2h_roundcube
        restart: always
        ports:
           - "8888:80"  # Webmail erreichbar unter http://localhost:8080
        environment:
            ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mail.key2host.com
            ROUNDCUBEMAIL_SMTP_SERVER: tls://mail.key2host.com
            ROUNDCUBEMAIL_SMTP_PORT: 587
            ROUNDCUBEMAIL_DEFAULT_PORT: 993
            ROUNDCUBEMAIL_SMTP_USER: "%u"
            ROUNDCUBEMAIL_SMTP_PASS: "%p"
        depends_on:
            - mailserver
        networks:
             - network
    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            HIDE_PHP_VERSION: true
        depends_on:
            - database
        networks:
            - network
networks:
    network:
        driver: bridge
volumes:
    db:
