services:
    webproxyserver:
        container_name: k2h_webproxyserver
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - webserver
        networks:
            - network
    webserver:
        container_name: k2h_webserver
        build:
            context: ./apache2
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    database:
        container_name: k2h_database
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: johnpw
            MYSQL_DATABASE: john
            MYSQL_USER: john
            MYSQL_PASSWORD: johnpw
        volumes:
            - db:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - network
    phpmyadmin:
        container_name: k2h
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
        depends_on:
            - database
        links:
           - database
        networks:
           - network
networks:
  network:
    driver: bridge
volumes:
  db: