services:
    proxy:
        container_name: k2h_proxy
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - webserver
        networks:
            - network
    webserver:
        container_name: k2h_webserver
        build:
            context: ./apache2
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network
    database:
        container_name: k2h_database
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: johnpw
            MYSQL_DATABASE: john
            MYSQL_USER: john
            MYSQL_PASSWORD: johnpw
        volumes:
            - db:/var/lib/mysql
        networks:
            - network
    saci:
        container_name: k2h_saci
        build:
            context: ./saci
            dockerfile: Dockerfile
        restart: always
        networks:
            - network
    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            HIDE_PHP_VERSION: true
        depends_on:
            - database
        links:
           - database
        networks:
           - network
    mailserver:
        container_name: k2h_mailserver
        image: ghcr.io/docker-mailserver/docker-mailserver:latest
        hostname: key2host.com
        ports:
           - "25:25"
           - "465:465"
           - "587:587"
           - "993:993"
        environment:
           - ENABLE_RSPAMD=1
        networks:
            - network
    webmail:
        container_name: k2h_webmail
        image: roundcube/roundcubemail
        environment:
           ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mailserver
           ROUNDCUBEMAIL_SMTP_SERVER: ssl://mailserver
           ROUNDCUBEMAIL_INSTALL_PLUGINS: 1
           ROUNDCUBEMAIL_PLUGINS: password, zipdownload, markasjunk, archive
           ROUNDCUBEMAIL_ASPELL_DICTS: de, en
           ROUNDCUBEMAIL_DB_TYPE: mysql
           ROUNDCUBEMAIL_DB_HOST: database
           ROUNDCUBEMAIL_DB_PORT: 3306
           ROUNDCUBEMAIL_DB_USER: wmusr
           ROUNDCUBEMAIL_DB_PASSWORD: 7U05K234hKohhQWa
           ROUNDCUBEMAIL_DB_NAME: webmail
        depends_on:
            - database
            - mailserver
        links:
           - database
           - mailserver
        networks:
            - network
networks:
  network:
    driver: bridge
volumes:
  db:
