services:

    proxy:
        container_name: k2h_proxy
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - webserver
        networks:
            - network

    webserver:
        container_name: k2h_webserver
        build:
            context: ./apache2
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network

    database:
        container_name: k2h_database
        build:
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: johnpw
            MYSQL_DATABASE: john
            MYSQL_USER: john
            MYSQL_PASSWORD: johnpw
        volumes:
            - db:/var/lib/mysql
        networks:
            - network

    saci:
        container_name: k2h_saci
        build:
            context: ./saci
            dockerfile: Dockerfile
        restart: always
        networks:
            - network

    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            HIDE_PHP_VERSION: true
        depends_on:
            - database
        links:
            - database
        networks:
            - network

    webmail:
        container_name: k2h_webmail
        image: roundcube/roundcubemail
        environment:
            ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mailserver
            ROUNDCUBEMAIL_SMTP_SERVER: ssl://mailserver
            ROUNDCUBEMAIL_INSTALL_PLUGINS: 1
            ROUNDCUBEMAIL_PLUGINS: password, zipdownload, markasjunk, archive
            ROUNDCUBEMAIL_ASPELL_DICTS: de, en
            ROUNDCUBEMAIL_DB_TYPE: mysql
            ROUNDCUBEMAIL_DB_HOST: database
            ROUNDCUBEMAIL_DB_PORT: 3306
            ROUNDCUBEMAIL_DB_USER: wmusr
            ROUNDCUBEMAIL_DB_PASSWORD: 7U05K234hKohhQWa
            ROUNDCUBEMAIL_DB_NAME: webmail
        depends_on:
            - database
            - mailserver
        links:
            - database
            - mailserver
        networks:
            - network

    mailserver:
        image: ghcr.io/docker-mailserver/docker-mailserver:latest
        container_name: mailserver
        hostname: key2host.com
        env_file: ./mailserver/config.env
        ports:
            - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
            - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
            - "465:465"  # ESMTP (implicit TLS)
            - "587:587"  # ESMTP (explicit TLS => STARTTLS)
            - "993:993"  # IMAP4 (implicit TLS)
        volumes:
            - maildata:/var/mail/
            - mailstate:/var/mail-state/
            - maillogs:/var/log/mail/
            - mailconfig:/tmp/docker-mailserver/
            - /etc/localtime:/etc/localtime:ro
        restart: always
        networks:
            - network

networks:
  network:
    driver: bridge
volumes:
  db:
  maildata:
  mailstate:
  maillogs:
  mailconfig:
