services:

    proxy:
        container_name: k2h_proxy
        build:
            context: ./proxy
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - webserver
        networks:
            - network

    database:
        container_name: k2h_database
        build:
            context: ./db
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: johnpw
            MYSQL_DATABASE: john
            MYSQL_USER: john
            MYSQL_PASSWORD: johnpw
        volumes:
            - db:/var/lib/mysql
        networks:
            - network

    saci:
        container_name: k2h_saci
        build:
            context: ./apps/saci
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network

    landing:
        container_name: k2h_landing
        build:
            context: ./apps/landing
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - network

    phpmyadmin:
        container_name: k2h_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        environment:
            PMA_HOST: database
            HIDE_PHP_VERSION: true
        depends_on:
            - database
        links:
            - database
        networks:
            - network

networks:
    network:
        driver: bridge

volumes:
    db:
