#!/bin/sh
set -e

# Portainer
docker rm  portainer -f
docker pull portainer/portainer-ce:latest
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

# System Services laden
systemctl daemon-reload
systemctl enable k2h.service

# Fail2Ban
systemctl enable fail2ban
systemctl start fail2ban

# UFW
echo "Konfiguriere Firewall..."
ufw --force enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 80/tcp        # HTTP
ufw allow 443/tcp       # HTTPS
ufw allow 22/tcp        # SSH
ufw allow 25/tcp        # 
ufw allow 143/tcp       # IMAP4 (explicit TLS => STARTTLS)
ufw allow 465/tcp       # ESMTP (implicit TLS)
ufw allow 587/tcp       # ESMTP (explicit TLS => STARTTLS)
ufw allow 993/tcp       # IMAP4 (implicit TLS)

ufw logging on

# ClamAV
echo "Konfiguriere Antivirus..."
(crontab -l; echo "0 3 * * * /usr/bin/freshclam --quiet") | crontab -
(crontab -l; echo "30 4 * * * /usr/bin/clamscan -r /etc /var /home /usr/local /tmp -i --log=/var/log/clamav/scan.log") | crontab -
systemctl enable clamav-daemon
systemctl start clamav-daemon

# Update Cronjob
CRONJOB="0 4 * * * /var/k2h/updater/k2h-updater.sh >> /var/log/k2h-updater.log 2>&1"

# Prüfen, ob der Cronjob bereits existiert
( crontab -l 2>/dev/null | grep -Fxq "$CRONJOB" ) || (
  # Wenn nicht, dann anhängen
  ( crontab -l 2>/dev/null; echo "$CRONJOB" ) | crontab -
  echo "[INFO] Cronjob hinzugefügt."
)

# Zertifikat ausstellen oder erneuern
if [ ! -f "/var/k2h/mailsrv/certs/fullchain.pem" ] || [ ! -f "/var/k2h/mailsrv/certs/privkey.pem" ]; then
    echo "[INFO] Zertifikat fehlt – erzwinge Ausstellung"
    if ! sudo certbot certonly --standalone \
        -d mail.key2host.com \
        --agree-tos \
         --email webmaster@key2host.com \
        --non-interactive \
        --force-renewal;
    then
        echo "[FEHLER] Zertifikatsausstellung fehlgeschlagen." >&2
        exit 1
    fi
else
  echo "[INFO] Zertifikat vorhanden – prüfe ggf. Erneuerung"
  if ! sudo certbot certonly --standalone \
    -d mail.key2host.com \
    --agree-tos \
    --email webmaster@key2host.com \
    --non-interactive
    then
        echo "[FEHLER] Zertifikatsausstellung fehlgeschlagen." >&2
        exit 1
    fi
fi

# !!! ADD --staging FOR TESTING !!!

# Symbolische Links setzen (zeigt auf aktuelle Version in /etc/letsencrypt)
sudo mkdir -p /var/k2h/mailsrv/certs/
sudo ln -sf /etc/letsencrypt/live/mail.key2host.com/fullchain.pem /var/k2h/mailsrv/certs/fullchain.pem
sudo ln -sf /etc/letsencrypt/live/mail.key2host.com/privkey.pem /var/k2h/mailsrv/certs/privkey.pem

# Berechtigungen korrekt setzen
sudo chmod 644 /etc/letsencrypt/live/mail.key2host.com/fullchain.pem
sudo chmod 600 /etc/letsencrypt/live/mail.key2host.com/privkey.pem

echo "Pre-Installation abgeschlossen."
echo "---"

# Neustart
echo "Das System wird neu gestartet, um die Änderungen anzuwenden."

systemctl reboot
