#!/bin/bash
set -e

packages=("fail2ban" "ufw" "clamav" "docker-ce")
for package in "${packages[@]}"; do
  if ! dpkg -l | grep -q "$package"; then
    echo "$package ist nicht installiert."
    exit 1
  else
    echo "$package ist bereits installiert."
  fi
done

# Portainer
docker volume create portainer_data
docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest

# System Services laden
systemctl daemon-reload
systemctl enable k2h.service
systemctl start k2h.service

# Fail2Ban
systemctl enable fail2ban
systemctl start fail2ban

# UFW
echo "Konfiguriere Firewall..."
#ufw --force enable
#ufw default deny incoming
#ufw default allow outgoing
#ufw allow 80/tcp
#ufw allow 443/tcp
#ufw allow 22/tcp
#ufw allow 21/tcp
ufw logging on

# ClamAV
echo "Konfiguriere Anti Virus..."
(crontab -l; echo "0 3 * * * /usr/bin/freshclam --quiet") | crontab -
(crontab -l; echo "30 4 * * * /usr/bin/clamscan -r /etc /var /home /usr/local /tmp -i --log=/var/log/clamav/scan.log") | crontab -
systemctl enable clamav-daemon
systemctl start clamav-daemon


# Unattended Upgrades
echo "Konfiguriere Automatische Updates..."
systemctl enable unattended-upgrades
systemctl start unattended-upgrades
(crontab -l; echo "0 3 * * * /usr/bin/unattended-upgrades -d") | crontab -

echo "Pre-Installation abgeschlossen."
echo "---"

# Countdown von 10 Sekunden
echo "Das System wird neu gestartet um die Änderungen anzuwenden."
echo "Drücken Sie Strg+C, um den Neustart abzubrechen."
for i in {15..1}
do
    if [ $i -eq 1 ]; then
        echo -ne "-> $i Sekunde verbleibt...\r"  # Einzahl
    else
        echo -ne "-> $i Sekunden verbleiben...\r"  # Mehrzahl
    fi
    sleep 1
done

# Sicherer Neustart des Systems
echo "Das System wird jetzt neu gestartet..."

shutdown -r now
