#!/bin/bash
set -e

packages=("ufw" "fail2ban" "clamav" "clamav-daemon" "docker-ce" "docker-ce-cli" "containerd.io" "docker-buildx-plugin" "docker-compose-plugin" "certbot")
for package in "${packages[@]}"; do
  if ! dpkg -l | grep -q "$package"; then
    echo "$package ist nicht verfügbar. Installiere das Paket um fortzufahren..."
    exit 1
  fi
done

if [ -d "/var/k2h/" ]; then
    systemctl stop k2h.service
fi