FROM certbot/certbot

RUN certbot certonly --webroot -w /etc/letsencrypt -d "key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "www.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "saci.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "app.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "auth.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "help.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "jobs.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com
RUN certbot certonly --webroot -w /etc/letsencrypt -d "status.key2host.com" --non-interactive --agree-tos --email webmaster@key2host.com