CREATE DATABASE IF NOT EXISTS webmail;
CREATE DATABASE IF NOT EXISTS mails;

CREATE USER IF NOT EXISTS 'wmusr'@'%' IDENTIFIED BY '7U05K234hKohhQWa';
CREATE USER IF NOT EXISTS 'musr'@'%' IDENTIFIED BY '7U05K234hKohhQWa';

GRANT ALL PRIVILEGES ON webmail.* TO 'wmusr'@'%';
GRANT ALL PRIVILEGES ON mails.* TO 'musr'@'%';

FLUSH PRIVILEGES;
