CREATE DATABASE IF NOT EXISTS webmail;

CREATE USER IF NOT EXISTS 'wmusr'@'%' IDENTIFIED BY 'pplsAAOV4I7U05K234hKohhQWaS4udO5aHIwsAyGYhmvDekn';

GRANT ALL PRIVILEGES ON webmail.* TO 'wmusr'@'%';

FLUSH PRIVILEGES;
